spring:
  application:
    name: restaurants

  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 12345

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    org:
      springframework:
        validation: debug
    web: debug