
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: restaurants

  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: 12345

  mvc:
    throw-exception-if-no-handler-found: false

  web:
    resources:
      add-mappings: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    org:
      springframework:
        validation: debug
    web: debug